DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS ProfileHasMilestones;
DROP TABLE IF EXISTS Milestones;
DROP TABLE IF EXISTS Note;
DROP TABLE IF EXISTS BMI;
DROP TABLE IF EXISTS Profile;
DROP TABLE IF EXISTS TracksActivities;
DROP TABLE IF EXISTS ActivityLocation;
DROP TABLE IF EXISTS Activities;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS FitnessGoal;
DROP TABLE IF EXISTS Login;
DROP TABLE IF EXISTS User;
DROP SCHEMA IF EXISTS fitnesstracker;

