INSERT INTO Location (Address, City, State, BuildingName) VALUES
('123 Main Street', 'Los Angeles', 'CA', 'Gym Plus'),
('456 Elm Street', 'New York', 'NY', 'Fit Zone'),
('789 Oak Street', 'Chicago', 'IL', 'Fitness World'),
('101 Pine Street', 'San Francisco', 'CA', 'Health Hub'),
('234 Maple Avenue', 'Miami', 'FL', 'Active Center'),
('567 Cedar Lane', 'Boston', 'MA', 'Peak Fitness'),
('890 Walnut Boulevard', 'Houston', 'TX', 'Body Works'),
('1122 Chestnut Street', 'Seattle', 'WA', 'Power Gym'),
('1313 Pinecrest Drive', 'Atlanta', 'GA', 'Iron Arena'),
('1414 Lakeview Avenue', 'Denver', 'CO', 'Stronghold Fitness'),
('1515 Sunset Boulevard', 'Phoenix', 'AZ', 'Vitality Gym'),
('1616 Spring Street', 'Philadelphia', 'PA', 'Fitness Fusion'),
('1717 Meadow Lane', 'Dallas', 'TX', 'Fit Flex'),
('1818 Park Place', 'Detroit', 'MI', 'Elite Fitness'),
('1919 River Road', 'Las Vegas', 'NV', 'Muscle Mansion'),
('2020 Grove Avenue', 'Orlando', 'FL', 'Fit Factory'),
('2121 Vine Street', 'San Diego', 'CA', 'Body Blast'),
('2222 Hillcrest Drive', 'Minneapolis', 'MN', 'Core Zone'),
('2323 Forest Lane', 'Portland', 'OR', 'Fitness Oasis'),
('2424 Summit Street', 'Charlotte', 'NC', 'Active Lifestyle'),
('2525 Broadway Street', 'Austin', 'TX', 'Endurance Gym'),
('2626 Ridge Road', 'Nashville', 'TN', 'Strength Studio'),
('2727 Park Avenue', 'San Antonio', 'TX', 'Fit Fusion'),
('2828 Lake Drive', 'Salt Lake City', 'UT', 'Body Sculpt'),
('2929 Cedar Avenue', 'Kansas City', 'MO', 'Fitness Junction');
