INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (1, "I really admire this profile!", 1, '2023-09-15');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (2, "Great job on your profile!", 2, '2023-11-20');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (3, "Your profile is truly inspiring.", 3, '2023-07-02');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (4, "This profile is fantastic!", 4, '2023-10-28');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (5, "Your profile content is amazing.", 5, '2023-06-10');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (6, "Impressive profile!", 6, '2023-12-05');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (7, "Keep up the great work!", 7, '2023-08-14');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (8, "Love what you're doing with your profile!", 8, '2023-11-02');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (9, "Your profile is top-notch!", 9, '2023-07-20');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (10, "Amazing content on your profile!", 10, '2023-10-01');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (11, "I'm really impressed by your profile.", 11, '2023-06-25');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (12, "This profile stands out!", 12, '2023-12-18');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (13, "Your profile is excellent!", 13, '2023-08-05');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (14, "Fantastic work on your profile!", 14, '2023-10-30');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (15, "Your profile content is really impressive.", 15, '2023-07-12');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (16, "I love your profile!", 16, '2023-11-10');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (17, "Your profile is simply amazing.", 17, '2023-09-08');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (18, "Great content on your profile!", 18, '2023-06-19');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (19, "Your profile is outstanding!", 19, '2023-12-02');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (20, "Impressive profile content!", 20, '2023-08-22');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (21, "Keep up the amazing work!", 21, '2023-11-15');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (22, "Your profile is truly remarkable.", 22, '2023-07-28');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (23, "I'm blown away by your profile!", 23, '2023-10-05');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (24, "This profile is outstanding!", 24, '2023-06-15');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (25, "Fantastic profile content!", 25, '2023-12-10');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (26, "Your profile is truly inspiring.", 26, '2023-09-18');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (27, "Great job on your profile!", 27, '2023-11-25');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (28, "Your profile is excellent!", 28, '2023-07-06');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (29, "This profile stands out!", 29, '2023-10-31');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (30, "Your profile is fantastic!", 30, '2023-06-22');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (31, "Impressive profile content!", 31, '2023-12-05');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (32, "Keep up the great work!", 32, '2023-08-16');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (33, "Amazing content on your profile!", 33, '2023-11-03');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (34, "I'm really impressed by your profile.", 34, '2023-07-22');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (35, "This profile stands out!", 35, '2023-10-10');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (36, "Your profile is top-notch!", 36, '2023-06-26');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (37, "Fantastic work on your profile!", 37, '2023-12-21');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (38, "Your profile is really impressive.", 38, '2023-09-12');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (39, "I love your profile!", 39, '2023-11-08');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (40, "Your profile is simply amazing.", 40, '2023-07-01');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (41, "Great content on your profile!", 41, '2023-10-26');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (42, "Impressive profile content!", 42, '2023-06-14');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (43, "Keep up the amazing work!", 43, '2023-12-09');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (44, "Your profile is truly remarkable.", 44, '2023-09-02');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (45, "I'm blown away by your profile!", 45, '2023-11-30');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (46, "This profile is outstanding!", 46, '2023-07-10');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (47, "Fantastic profile content!", 47, '2023-10-15');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (48, "Your profile is truly inspiring.", 48, '2023-06-18');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (49, "Great job on your profile!", 49, '2023-12-01');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (50, "Your profile is excellent!", 50, '2023-08-24');
INSERT INTO Comment (ProfileID, Content, UserID, PublishDate) VALUES (51, "This profile stands out!", 51, '2023-11-17');
